# Pre-commit hooks for agile-mcp quality checks
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Local custom hooks for MCP-specific validation (disabled until scripts exist)
  # - repo: local
  #   hooks:
  #     - id: json-response-validation
  #       name: Validate Tool Response Formats
  #       entry: scripts/validate_responses.py
  #       language: python
  #       files: ^src/agile_mcp/api/.*\.py$
  #       pass_filenames: true
  #       
  #     - id: critical-e2e-tests
  #       name: Run Critical E2E Tests (Production Server)
  #       entry: scripts/run_critical_tests.py --production-server
  #       language: python
  #       files: ^src/agile_mcp/(api|models|services)/.*\.py$
  #       pass_filenames: true
  #       
  #     - id: mcp-protocol-validation
  #       name: Validate MCP Protocol Compliance
  #       entry: scripts/validate_mcp_protocol.py
  #       language: python
  #       files: ^src/agile_mcp/api/.*\.py$
  #       pass_filenames: true

  # Code formatting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11
        
  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        
  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]
        
  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-setuptools]
        args: ["--ignore-missing-imports", "--no-strict-optional"]
        
  # Security scanning
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-r", "src/"]
        exclude: ^tests/
        
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements